### ISSUE TITLE
Cannot create a new file when combined with memoryfs

### ISSUE THREAD

**Issue by PhilAndrew** [puniverse/javafs#2]
When used with https://github.com/openCage/memoryfs

I have the following error messages.

[error]    unique: 82, error: -2 (No such file or directory), outsize: 16
[error] unique: 83, opcode: MKNOD (8), nodeid: 1, insize: 67
[error] create flags: 0xc1 /.t.txt.swp 0100600 umask=0022
[error] Sep 18, 2015 4:34:52 PM co.paralleluniverse.javafs.FuseFileSystemProvider errno
[error] WARNING: Exception
[error] java.lang.UnsupportedOperationException
[error]         at java.nio.file.spi.FileSystemProvider.newFileChannel(FileSystemProvider.java:476)
[error]         at de.pfabulist.lindwurm.eighty.EightyProvider.newFileChannel(EightyProvider.java:265)
[error]         at co.paralleluniverse.javafs.FuseFileSystemProvider.create(FuseFileSystemProvider.java:499)
[error]         at co.paralleluniverse.fuse.LoggedFuseFilesystem$7.invoke(LoggedFuseFilesystem.java:143)
[error]         at co.paralleluniverse.fuse.LoggedFuseFilesystem$7.invoke(LoggedFuseFilesystem.java:140)
[error]         at co.paralleluniverse.fuse.LoggedFuseFilesystem.log(LoggedFuseFilesystem.java:53)
[error]         at co.paralleluniverse.fuse.LoggedFuseFilesystem.create(LoggedFuseFilesystem.java:140)
[error]         at co.paralleluniverse.fuse.Filesystem._create(Filesystem.java:215)
[error]         at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$30.invoke(Unknown Source)

Who's fault is it, javafs or memoryfs?

**Comment by pron** [comment]
Can you try it with [Jimfs](https://github.com/google/jimfs)?
Can you try it with memoryfs directly?

**Comment by PhilAndrew** [comment]
I will try it with Jimfs now, what do you mean "Can you try it with memoryfs directly?"?

**Comment by pron** [comment]
I mean w/o JavaFS, but directly through the JavaAPI.

Also, I see you're using JavaFS's logging. Could you provide the log?

**Comment by PhilAndrew** [comment]
It works with Jimfs ok.

Here is the log of using it with memoryfs - I first create a directory test which works, I ls, I try to create a text file with vi and it fails.

https://gist.github.com/PhilAndrew/0ca1c80c1cb9a6acb93b

**Comment by pron** [comment]
The reason is that memoryfs doesn't support FileChannels.
I've updated JavaFS to work even without FileChannel support. Can you try again?

**Comment by PhilAndrew** [comment]
Hi, different errors. 

https://gist.github.com/PhilAndrew/0e415d359fbd4910283d

So its maybe not your fault exactly but it would be nice if the two can play together. :)

**Comment by pron** [comment]
Well, the main problem now is the [failure of `write`](https://gist.github.com/PhilAndrew/0e415d359fbd4910283d#file-loglog-log-L677), and that's caused by the wrong assumption on the part of memoryfs [here](https://github.com/openCage/memoryfs/blob/master/src/main/java/de/pfabulist/lindwurm/memory/ByteArrayChannel.java#L108) that a `ByteBuffer` has an array (wrong for native buffers). There is nothing I can do about that. Maybe open a memoryfs bug.

But Jimfs works, and Jimfs provides the same functionality as memoryfs.

**Comment by PhilAndrew** [comment]
Yes I may be looking at jimfs instead

**Comment by PhilAndrew** [comment]
It works well with jimfs,  after  testing happy. I guess you know that.
